services:
  - type: web
    name: judgment-api
    runtime: python
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:8080 judgment_api:app"
    plan: free
